/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness, application version, and contract revision
         * @description One of the five endpoints that does not require a session.
         *
         *     `version` is the application release, stamped from the release tag at build time (ADR 0016); a build from source reports `dev`. `api_version` is the HTTP contract revision and changes only when a new `/api/vN` prefix ships.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the client should render: setup, login, or the library
         * @description Does not require a session, and answers differently depending on whether one is present.
         *
         *     This is the one response every screen already fetches, which is why several unrelated facts are reported here rather than from an endpoint of their own.
         */
        get: operations["getAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the first administrator
         * @description Only while the server is unconfigured; once an account exists this answers `409 conflict`. Issues a session cookie on success.
         */
        post: operations["postAuthSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a username and password for a session
         * @description Throttled per client IP. **A wrong username and a wrong password are reported identically** as `401 unauthorized`, deliberately: distinguishing them tells an attacker which half they got right.
         */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End this session only
         * @description Ends the calling session and no other. Contrast `/auth/password`, which revokes every session this account holds.
         */
        post: operations["postAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change your own password
         * @description Changes the calling account's password and **revokes every session that account holds, including this one**. That is the point of server-side sessions, not a bug to smooth over — a client must expect the next request to be answered `401` and send the user back to the login screen.
         */
        post: operations["postAuthPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This server's own cryptographic identity
         * @description Who this server is when it talks to another one (ADR 0044). `fingerprint_display` is the same value grouped for a human to read aloud or compare by eye.
         */
        get: operations["getIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every library on this server */
        get: operations["listLibraries"];
        put?: never;
        /**
         * Create a library
         * @description Administrators only.
         *
         *     `roots` is the multi-location form (ADR 0034). `path` remains accepted and means exactly the same as a single-element `roots` array, so every client that predates multi-root libraries keeps working unchanged. Send one or the other.
         */
        post: operations["createLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The library's id. */
                id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a library and its rows
         * @description Administrators only. Removes the library's **records**. It does not touch the media on disk — the server never owns the files.
         */
        delete: operations["deleteLibrary"];
        options?: never;
        head?: never;
        /**
         * Rename a library, move it, or change its kind
         * @description Administrators only. Every field is optional; an omitted field is left alone, which is why they are nullable pointers on the server rather than plain strings.
         */
        patch: operations["patchLibrary"];
        trace?: never;
    };
    "/libraries/{id}/roots": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The library's id. */
                id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        /** The locations this library's files live in */
        get: operations["listLibraryRoots"];
        put?: never;
        /**
         * Add a location to this library
         * @description Administrators only.
         */
        post: operations["addLibraryRoot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{id}/roots/{rootID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The library's id. */
                id: components["parameters"]["LibraryId"];
                /** @description The root's id. */
                rootID: components["parameters"]["RootId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a location from this library
         * @description Administrators only. Removes the rows that came from that location; the files are untouched.
         */
        delete: operations["deleteLibraryRoot"];
        options?: never;
        head?: never;
        /**
         * Point a location somewhere else
         * @description Administrators only. Used when a drive letter changes or a share moves.
         */
        patch: operations["patchLibraryRoot"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The single error shape. Handlers never surface raw SQL errors. */
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        Error: {
            /**
             * @description A stable, switchable identifier. **An open set** — a new code is an additive change (ADR 0018), so a client must tolerate one it does not know. Codes in use: `bad_request` (400), `unauthorized` (401), `forbidden` (403), `not_found` (404), `conflict` (409), `too_many_requests` (429), `unsupported_api_version` (400), `unavailable` (503), `canceled` (499), `internal` (500).
             * @example not_found
             */
            code: string;
            /**
             * @description Human-readable, and not intended to be parsed.
             * @example no item with id 412
             */
            message: string;
        };
        /** @description A bare acknowledgement. Present so that a client that decodes every response has something to decode. */
        Acknowledged: {
            ok?: boolean;
        };
        Health: {
            /** @example ok */
            status: string;
            /**
             * @description The application release, semver, stamped from the release tag at build time. A build straight from source reports `dev`, which is the honest label for it.
             * @example 0.8.58
             * @example dev
             */
            version: string;
            /**
             * @description The contract revision being served. Permanently 1 at `/api`.
             * @example 1
             */
            api_version: number;
            /** @description Every revision this build can serve. A list, because a future v2 server keeps answering v1 for at least one release — "which versions do you speak" is a different question from "which one am I getting". */
            api_versions: number[];
        };
        User: {
            /**
             * @description **A string, not a number.** Item and library ids are integers; user ids are not.
             * @example u_3f9
             */
            id: string;
            name: string;
            /**
             * @description An open set. `admin` and `member` today (ADR 0015).
             * @example admin
             * @example member
             */
            role: string;
            /**
             * @description This account's own activity-sharing choice (ADR 0035). Carried on `/auth/status` only, and **absent rather than false** when the server could not read it.
             *
             *     It is here because there is nowhere else it could be: `GET /api/people` excludes the caller by design, so a client had no way to read back a setting it could write, and the toggle rendered unticked for somebody who had opted in. For a privacy control that is the worst direction to be wrong in.
             */
            sharing?: boolean;
            /** @description Whether this account appears in the roster handed to paired servers. `/auth/status` only, and absent rather than false when unreadable. */
            visible_to_peers?: boolean;
        };
        AuthStatus: {
            /** @description Whether any account exists. While false the API is open — but the server is forced onto `127.0.0.1`, so it is reachable only from the machine it runs on. */
            configured: boolean;
            authenticated: boolean;
            /** @description Whether the socket actually reaches beyond this machine — **not** whether a password is set. An unsecured server is always `false` because it is forced onto loopback; a secured server the operator deliberately bound to a loopback address is also `false`, and stays plain HTTP. TLS turns on at the same boundary that gates LAN binding (ADR 0014). */
            lan_enabled: boolean;
            /**
             * @description True only when restarting would actually bind wider than the server is bound right now: the loopback restriction is what is holding it back, *and* the configured address reaches further once lifted.
             *
             *     **Not the inverse of `lan_enabled`.** A server deliberately bound to loopback reports `false`, because a restart would change nothing there and a client that promises otherwise sends somebody to do something that cannot work.
             */
            restart_required: boolean;
            /**
             * @description Whether ffmpeg is present (ADR 0048). Reported to every caller, not only administrators — the install button is admin-only and correctly so, but the *fact* is not a secret and the person most affected is a member who cannot open Settings at all.
             *
             *     A client must use this to explain the failure **before** attempting playback: a `<video>` element handed a refused request reports a bare error with no status, so a client that waits to be told cannot be told, and the viewer sees a black rectangle instead of a reason.
             *
             *     **Absent must read as capable.** A client older than the server, or a server older than the client, may not see this field; assuming otherwise puts a warning in front of somebody whose playback works.
             */
            can_convert: boolean;
            /** @description Present only when a session is active. */
            user?: components["schemas"]["User"];
        };
        SetupRequest: {
            username: string;
            /** Format: password */
            password: string;
            /**
             * @description Optional, and **absent means no** — absent and `false` are deliberately different. Absent means the caller never saw the question, which is true of an older client and of any script.
             *
             *     Sending `true` starts a one-off background download of ffmpeg: around 160MB, pinned URL, checksum verified (ADR 0048). This is the one place the server may fetch anything on its own initiative, which is why it is an optional field rather than a boolean with a default. Only a client that displayed what would be downloaded, from where, how large and under which licence may send `true` — that disclosure *is* the consent, and it stands in for the admin gate that cannot exist before any account does.
             *
             *     Setup does not wait for the download, and a fetch that cannot start never fails the request. Nothing is fetched when ffmpeg is already present.
             */
            install_media_tools?: boolean;
        };
        SetupResponse: {
            configured: boolean;
            authenticated: boolean;
            /** @description Whether a download actually started. Poll `GET /api/media-tools` for progress. False when ffmpeg was already present, or when `install_media_tools` was not sent. */
            media_tools_installing: boolean;
            restart_required: boolean;
            user: components["schemas"]["User"];
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            authenticated: boolean;
            user: components["schemas"]["User"];
        };
        ChangePasswordRequest: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
        };
        Identity: {
            /** @description This server's public-key fingerprint (ADR 0044). */
            fingerprint: string;
            /** @description The same value, grouped for a human to read aloud or compare by eye. */
            fingerprint_display: string;
            name: string;
        };
        /** @description The last scan's verdict, when it had one. Carried on the library rather than only in live scan progress — which dies with the server process, and a warning about a kind that cannot be changed needs to outlive a restart. */
        ShapeWarning: {
            code: string;
            message: string;
            remedy?: string;
        };
        /** @description One place a library's files live (ADR 0034). */
        LibraryRoot: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            library_id: number;
            path: string;
            /**
             * Format: int64
             * @description Unix seconds.
             */
            created_at: number;
            /** @description Rows that would go with this location if it were removed. */
            item_count: number;
        };
        Library: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @description **An open set.** `movie`, `show`, `music` and `picture` today; a new kind is an additive change, so a client with an exhaustive switch is relying on a guarantee this contract does not give. */
            kind: string;
            /**
             * @description The library's first location.
             *
             *     Kept by the server so clients that predate multi-root libraries keep working, and superseded by `roots`. Read `roots` for anything that has to be right about a library in more than one place; this stays correct for the single-location case, which is most of them.
             */
            path: string;
            roots?: components["schemas"]["LibraryRoot"][];
            /**
             * Format: int64
             * @description Unix seconds.
             */
            created_at: number;
            /**
             * Format: int64
             * @description Unix seconds, or null if it has never been scanned.
             */
            scanned_at: number | null;
            /** @description Tiles in the grid. */
            item_count: number;
            /** @description Files in the library — songs, photos, films, episodes — as against `item_count`, which is tiles in the grid. They differ wherever a library groups its media: 1,171 artists holding tens of thousands of songs. */
            media_count: number;
            shape_warning?: components["schemas"]["ShapeWarning"];
        };
        LibraryList: {
            libraries: components["schemas"]["Library"][];
        };
        RootList: {
            roots: components["schemas"]["LibraryRoot"][];
        };
        CreateLibraryRequest: {
            name: string;
            /** @description `movie`, `show`, `music` or `picture`. Validated on the way in, so this is a closed set for *requests* even though it is open for responses. */
            kind: string;
            /** @description The single-location form. Means the same as a one-element `roots`. */
            path?: string;
            /** @description The multi-location form (ADR 0034). */
            roots?: string[];
        };
        /** @description Every field optional; an omitted field is left alone. */
        PatchLibraryRequest: {
            name?: string;
            path?: string;
            kind?: string;
        };
        RootRequest: {
            path: string;
        };
    };
    responses: {
        /** @description Malformed body or invalid parameter. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No session, or a session that is no longer valid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Signed in, but not permitted — an administrator-only route, or a state-changing request whose `Origin` did not match. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description The library's id. */
        LibraryId: number;
        /** @description The root's id. */
        RootId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Always. An unauthenticated caller gets the same shape without `user`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    postAuthSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description The administrator was created and this caller is now signed in as them. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description An account already exists, so there is no first administrator to create. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. The session cookie is set on this response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Incorrect username or password — the two are not distinguished. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description No accounts exist yet; the caller wants `/auth/setup`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too many attempts from this client; wait a few minutes. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    postAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is gone and the cookie has been cleared. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acknowledged"];
                };
            };
        };
    };
    postAuthPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Changed. Every session for this account, including the caller's, is now invalid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acknowledged"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This server's identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listLibraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All libraries, with their counts and last-scan verdict. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLibraryRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A library already covers that path. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deleteLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The library's id. */
                id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acknowledged"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The library's id. */
                id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchLibraryRequest"];
            };
        };
        responses: {
            /** @description The library as it now stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listLibraryRoots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The library's id. */
                id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every root, each carrying the number of rows that would go with it if it were removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addLibraryRoot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The library's id. */
                id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RootRequest"];
            };
        };
        responses: {
            /** @description Added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryRoot"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description That path is already covered by a library. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deleteLibraryRoot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The library's id. */
                id: components["parameters"]["LibraryId"];
                /** @description The root's id. */
                rootID: components["parameters"]["RootId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acknowledged"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchLibraryRoot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The library's id. */
                id: components["parameters"]["LibraryId"];
                /** @description The root's id. */
                rootID: components["parameters"]["RootId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RootRequest"];
            };
        };
        responses: {
            /** @description The root as it now stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryRoot"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
